---
# tasks file for postgresql-ocp

- name: Set OpenShift Objects for Postgresql to {{ _postgresql_state }}
  k8s:
    state: "{{ _postgresql_state }}"
    merge_type:
    - strategic-merge
    - merge
    definition: "{{ lookup('template', item ) | from_yaml }}"
  loop:
  - secret.yml.j2
  - service.yml.j2
  - deployment.yml.j2

- name: Set PersistentVolumeClaim for Postgresql to {{ _postgresql_state }}
  when:
  - _postgresql_persistent|bool
  k8s:
    state: "{{ _postgresql_state }}"
    merge_type:
    - strategic-merge
    - merge
    definition: "{{ lookup('template', 'persistent_volume_claim.yml.j2' ) | from_yaml }}"

- name: Wait until application is available
  when:
  - _postgresql_state == "present"
  - _postgresql_wait_for_init|bool
  k8s_facts:
    api_version: apps/v1
    kind: Deployment
    name: "{{ _postgresql_name }}"
    namespace: "{{ _postgresql_namespace }}"
  register: r_deployment
  until:
  - r_deployment.resources[0].status.availableReplicas is defined
  - r_deployment.resources[0].status.availableReplicas == 1
  retries: 50
  delay: 10
